### ISSUE TITLE
Integration with Django

### ISSUE THREAD

**Issue by noodlebreak** [YosaiProject/yosai#4]
I'd try to do that myself, but if you use Django yourself, could you put down a few examples in the readme? Because that would be great.

Thanks.

**Comment by datamafia** [comment]
__up vote__.  I may try to wire this into 1.8 (LTS) and see how it spits back at me. Wanted to get on a thread for this should others start piling in.  Lib looks really good, excited to try it!

**Comment by Dowwie** [comment]
I doubt you caught my invitation on the django google group mailing list to work on a Django integration?  I'd gladly help anyone who is willing to dedicate effort to it.

**Comment by Dowwie** [comment]
@datamafia I noticed you're in NYC.  Why don't you go to the python nyc meetup this Thursday night and we can meet?

**Comment by noodlebreak** [comment]
Just to be sure, guys would Yosai fill the role of being also a row level permissions framework we could use with Django models?

**Comment by andreyrusanov** [comment]
I'm also interested in Django support. I was going to make integration with Django Rest Framework, but it would be logical to start with Django itself.

**Comment by Dowwie** [comment]
This is the sort of valuable discussion meant for a discussion forum, such as the Yosai google group that I've created.  Feel free to make use of it:   yosai@googlegroups.com

**Comment by Dowwie** [comment]
@noodlebreak  row-level security sounds like a database concept (such as that which was just released in Postgresql) is this what you're asking about?

**Comment by Dowwie** [comment]
let's continue talk in the google group

**Comment by datamafia** [comment]
Sorry to reopen...

@Dowwie I am not back in NYC until next week. #onTheRoad -- I would love to hook up regardless. 

I have most Google services deliberately disabled on my account - so no Google Groups. I am happy spinning up a private repo for a small civil group to talk/comment/hack at an integration. 

I also need to read the docs (OMG right?) and see how/what the internal API looks like. 

I suspect this project can slip in via middleware into Django (thoughts?). Will need decorators also for views+, and then there is admin...

This would be a solid asset for DjangoRest @andreyrusanov - love to connect w/DjangoRest users as I need to "skill up".  Putting an integration into Django (proper) will get more eyes on the work, and since this is an ACL/security feature that is a huge asset. Should we have great success I would be very happy to contribute further.

**Comment by Dowwie** [comment]
@datamafia  send me a message by messenger pigeon if you need to , otherwise dkcdkg  at gmail
